### ISSUE TITLE
Automate PyPI Releases

### ISSUE THREAD

**Issue by dacort** [dacort/athena-federation-python-sdk#10]
Ideally we can automate releases of PyPI: Good example here: https://www.caktusgroup.com/blog/2021/02/11/automating-pypi-releases/

```yaml
name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
```
